// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://xwtzzysvuyiunbxgocxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dHp6eXN2dXlpdW5ieGdvY3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTA2MjEsImV4cCI6MjA2NDAyNjYyMX0.sydY1-wDG4cCXlVqamXvR_j23hX56tD4MUR76_hwq30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
